version: '3'
services:
  api:
    image: gcr.io/cnsa2020-jrz899/covidapi:1.0
    container_name: covidapi-container
    volumes:
      - ./apikey.json:/tmp/keys/apikey.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/apikey.json
    ports:
       - "4000:4000"
  app:
    image: gcr.io/cnsa2020-jrz899/covidapp:1.0
    container_name: covidapp-container
    ports:
       - "80:8080"

