version: '3' 
services: 
  api:
#   Construcción a parte para hacerla con Jenkins
#    build: .
    image: gcr.io/cnsa2020-jrz899/covidapi:1.0
    container_name: covidapi-container
    network_mode: "host"
    expose:
      - "4000"
  app:
#   Construcción a parte para hacerla con Jenkins
#    build: client/
    image: gcr.io/cnsa2020-jrz899/covidapp:1.0
    container_name: covidapp-container
    network_mode: "host"
    expose:
      - "8080"
    depends_on:
      - api
